=== danpr/knut/knutsetting4/xmlconf/modules.dtd
<?xml version="1.0" ?>
<!ELEMENT Modules (Driver+)>
<!ELEMENT Driver (Description?, DistinguishName?, Port+, ParamList?)>
<!ELEMENT Description (#PCDATA)>
<!ELEMENT DistinguishName (#PCDATA)>
<!ATTLIST Driver name NMTOKEN #REQUIRED>
<!ELEMENT Port (PortNameList, PortSpeed, PortBits)>
<!ATTLIST Port type ( serial | usb ) #REQUIRED
               auto ( yes | no | def | only ) #REQUIRED>
<!ELEMENT PortNameList (PortName+)>
<!ELEMENT PortName EMPTY>
<!ATTLIST PortName value CDATA #REQUIRED>
<!ELEMENT PortSpeed EMPTY>
<!ATTLIST PortSpeed value (600 | 1200 | 2400 | un) #REQUIRED>
<!ELEMENT PortBits EMPTY>
<!ATTLIST PortBits value (7 | 8 | un) #REQUIRED>
<!ELEMENT ParamList (ParamNumber | ParamString | ParamEnum )+>
<!ELEMENT ParamNumber (ParamMinimum?, ParamMaximum?,ParamNumberDefault?)>
<!ATTLIST ParamNumber force (yes | no) #REQUIRED
                      name NMTOKEN #REQUIRED>
<!ELEMENT ParamNumberDefault EMPTY>
<!ATTLIST ParamNumberDefault value NMTOKEN #REQUIRED>
<!ELEMENT ParamMinimum EMPTY>
<!ATTLIST ParamMinimum value NMTOKEN #REQUIRED>
<!ELEMENT ParamMaximum EMPTY>
<!ATTLIST ParamMaximum value NMTOKEN #REQUIRED>
<!ELEMENT ParamString (ParamStringDefault?) >
<!ATTLIST ParamString force (yes | no) #REQUIRED
                      name NMTOKEN #REQUIRED
                      variable (yes | no) #REQUIRED>
<!ELEMENT ParamStringDefault (#PCDATA)>

<!ELEMENT ParamEnum (ParamEnumDefault?, ParamEnumValueList)>
<!ATTLIST ParamEnum force (yes | no) #REQUIRED
                    name NMTOKEN #REQUIRED>
<!ELEMENT ParamEnumDefault EMPTY>
<!ATTLIST ParamEnumDefault value NMTOKEN #REQUIRED>
<!ELEMENT ParamEnumValueList (ParamEnumValue+)>
<!ELEMENT ParamEnumValue (#PCDATA)>
<!ATTLIST ParamEnumValue value NMTOKEN #REQUIRED>

=== danpr/knut/knutsetting4/xmlconf/modules_def.xml
<?xml version="1.0"?>
<!DOCTYPE Modules SYSTEM "modules.dtd">
<Modules>
  <Driver name="apcsmart">
    <Description>For  all recent APC models that use a serial protocol at 2400  bps</Description> 
    <Port type="serial" auto="no">
       <PortNameList>
         <PortName value ="/dev/ttyS0"/>
         <PortName value ="/dev/ttyS1"/>
         <PortName value ="/dev/ttyS2"/>
         <PortName value ="/dev/ttyS3"/>
       </PortNameList>
      <PortSpeed value="2400"/>
      <PortBits value ="un"/>
    </Port>
    <ParamList>
      <ParamString force="no" name="cable" variable="no">
        <ParamStringDefault>940-0095B</ParamStringDefault>
      </ParamString>
      <ParamEnum force="no" name="sdtype">
        <ParamEnumValueList>
          <ParamEnumValue value="0">soft shutdown or powerdown, depending on battery status</ParamEnumValue>
          <ParamEnumValue value="1">soft shutdown followed by powerdown</ParamEnumValue>
          <ParamEnumValue value="2">instant power off</ParamEnumValue>
          <ParamEnumValue value="3">power off with grace period</ParamEnumValue>
          <ParamEnumValue value="4">'force OB' hack method for CS 350</ParamEnumValue>
        </ParamEnumValueList>
      </ParamEnum>
    </ParamList>
  </Driver>

  <Driver name="bcmxcp_usb">
    <Description>For BCM/XCP-compatible UPSes over USB. (Powerware PW5115 or PW3501)</Description> 
    <Port type="usb" auto="yes">
       <PortNameList>
         <PortName value ="/dev/usb/hid/hiddev0"/>
         <PortName value ="/dev/usb/hid/hiddev1"/>
         <PortName value ="/dev/usb/hid/hiddev2"/>
         <PortName value ="/dev/usb/hid/hiddev3"/>
       </PortNameList>
      <PortSpeed value="un"/>
      <PortBits value ="un"/>
    </Port>
     <ParamList>
       <ParamNumber force="no" name="shutdown_delay">
         <ParamMinimum value="0"/>
         <ParamMaximum value="9999"/>
         <ParamNumberDefault value="120"/>
       </ParamNumber>
     </ParamList>
  </Driver>



  <Driver name="bcmxcp">
    <Description>For BCM/XCP-compatible UPSes. (Powerware PW5115 or PW9120)</Description> 
    <Port type="serial" auto="no">
       <PortNameList>
         <PortName value ="/dev/ttyS0"/>
         <PortName value ="/dev/ttyS1"/>
         <PortName value ="/dev/ttyS2"/>
         <PortName value ="/dev/ttyS3"/>
       </PortNameList> 	 
      <PortSpeed value="un"/>
      <PortBits value ="un"/>
    </Port>
     <ParamList>
       <ParamNumber force="no" name="shutdown_delay">
         <ParamMinimum value="0"/>
         <ParamMaximum value="9999"/>
         <ParamNumberDefault value="180"/>
       </ParamNumber>
       <ParamEnum force="no" name="baud_rate">
         <ParamEnumDefault value="none"/>
         <ParamEnumValueList>
           <ParamEnumValue value="none">baudhunting</ParamEnumValue>
           <ParamEnumValue value="1200">1200 bd</ParamEnumValue>
           <ParamEnumValue value="2400">2400 bd</ParamEnumValue>
           <ParamEnumValue value="4800">4800 bd</ParamEnumValue>
           <ParamEnumValue value="9600">9600 bd</ParamEnumValue>
           <ParamEnumValue value="19200">19200 bd</ParamEnumValue>
         </ParamEnumValueList>
      </ParamEnum>
     </ParamList> 
  </Driver>



  <Driver name="belkin">
    <Description>For Regulator Pro 525 (F6C525-SER)</Description> 
    <Port type="serial" auto="no">
       <PortNameList>
         <PortName value ="/dev/ttyS0"/>
         <PortName value ="/dev/ttyS1"/>
         <PortName value ="/dev/ttyS2"/>
         <PortName value ="/dev/ttyS3"/>
       </PortNameList> 	 
      <PortSpeed value="un"/>
      <PortBits value ="un"/>
    </Port>
  </Driver>


  <Driver name="belkinunv">
    <Description>For Belkin Universal UPS models  F6C800-UNV  and  F6C120-UNV</Description> 
    <Port type="serial" auto="no">
       <PortNameList>
         <PortName value ="/dev/ttyS0"/>
         <PortName value ="/dev/ttyS1"/>
         <PortName value ="/dev/ttyS2"/>
         <PortName value ="/dev/ttyS3"/>
       </PortNameList> 	 
      <PortSpeed value="un"/>
      <PortBits value ="un"/>
    </Port>
    <ParamList>
      <ParamNumber force="no" name="wait">
        <ParamMinimum value="10"/>
        <ParamMaximum value="90"/>
        <ParamNumberDefault value="30"/>
      </ParamNumber>
      <ParamString force="no" name="nohang" variable="no"/>
      <ParamString force="no" name="flash" variable="no"/>
      <ParamString force="no" name="silent" variable="no"/>
      <ParamString force="no" name="dumbterm" variable="no"/>
    </ParamList>
  </Driver>
 


  <Driver name="bestfcom">
    <Description>For Best Power Fortress/Ferrups UPSes. (Fortress UPS Protocol)</Description> 
    <Port type="serial" auto="no">
       <PortNameList>
         <PortName value ="/dev/ttyS0"/>
         <PortName value ="/dev/ttyS1"/>
         <PortName value ="/dev/ttyS2"/>
         <PortName value ="/dev/ttyS3"/>
       </PortNameList> 	 
      <PortSpeed value="un"/>
      <PortBits value ="un"/>
    </Port>
  </Driver>



  <Driver name="bestfortress">
    <Description>For old Best Fortress UPS.</Description>
    <Port type="serial" auto="no">
       <PortNameList>
         <PortName value ="/dev/ttyS0"/>
         <PortName value ="/dev/ttyS1"/>
         <PortName value ="/dev/ttyS2"/>
         <PortName value ="/dev/ttyS3"/>
       </PortNameList>
      <PortSpeed value="un"/>
      <PortBits value ="un"/>
    </Port>
    <ParamList>
      <ParamString force="no" name="max_load" variable="yes"/>
       <ParamEnum force="no" name="baudrate">
         <ParamEnumDefault value="2400"/>
         <ParamEnumValueList>
           <ParamEnumValue value="1200">1200 bd</ParamEnumValue>
           <ParamEnumValue value="2400">2400 bd</ParamEnumValue>
           <ParamEnumValue value="4800">4800 bd</ParamEnumValue>
           <ParamEnumValue value="9600">9600 bd</ParamEnumValue>
         </ParamEnumValueList>
      </ParamEnum>
    </ParamList>
  </Driver>




  <Driver name="bestups">
    <Description>For Fortress, Fortress Telecom, Axxium Rackmount and Patriot Pro</Description> 
    <Port type="serial" auto="no">
       <PortNameList>
         <PortName value ="/dev/ttyS0"/>
         <PortName value ="/dev/ttyS1"/>
         <PortName value ="/dev/ttyS2"/>
         <PortName value ="/dev/ttyS3"/>
       </PortNameList> 	 
      <PortSpeed value="un"/>
      <PortBits value ="un"/>
    </Port>
    <ParamList>
      <ParamNumber force="no" name="nombattvolt">
         <ParamMinimum value="10"/>
         <ParamMaximum value="100"/>
        <ParamNumberDefault value="27"/>
      </ParamNumber>
      <ParamString force="no" name="ID" variable="yes"/>
      <ParamNumber force="no" name="battvoltmult">
         <ParamMinimum value="1"/>
         <ParamMaximum value="100"/>
        <ParamNumberDefault value="1"/>
      </ParamNumber>
    </ParamList>
  </Driver>

  <Driver name="bestuferrups">
    <Description>For Best Power Micro-Ferrups ME3100</Description> 
    <Port type="serial" auto="no">
       <PortNameList>
         <PortName value ="/dev/ttyS0"/>
         <PortName value ="/dev/ttyS1"/>
         <PortName value ="/dev/ttyS2"/>
         <PortName value ="/dev/ttyS3"/>
       </PortNameList> 	 
      <PortSpeed value="un"/>
      <PortBits value ="un"/>
    </Port>
  </Driver>

  <Driver name="blazer_ser">
    <Description>For Blazer, Energy Sistem, Fenton Technologies, Mustek and many others with serial connection.</Description>
    <Port type="serial" auto="no">
       <PortNameList>
         <PortName value ="/dev/ttyS0"/>
         <PortName value ="/dev/ttyS1"/>
         <PortName value ="/dev/ttyS2"/>
         <PortName value ="/dev/ttyS3"/>
       </PortNameList>
      <PortSpeed value="un"/>
      <PortBits value ="un"/>
    </Port>
    <ParamList>
      <ParamString force="no" name="norating" variable="no"/> 
      <ParamString force="no" name="novendor" variable="no"/> 
      <ParamNumber force="no" name="offdelay">
        <ParamNumberDefault value="120"/>
      </ParamNumber>
      <ParamNumber force="no" name="ondelay">
        <ParamNumberDefault value="3"/>
      </ParamNumber>
      <ParamString force="no" name="runtimecal" variable="yes"/> 
      <ParamString force="no" name="chargetime" variable="yes"/> 
      <ParamString force="no" name="idleload" variable="yes"/> 
       <ParamEnum force="no" name="cablepower">
         <ParamEnumDefault value="normal"/>
         <ParamEnumValueList>
           <ParamEnumValue value="normal">The driver  will set DTR and clear RTS.</ParamEnumValue>
           <ParamEnumValue value="reverse">The driver  will clear DTR and set RTS.</ParamEnumValue>
           <ParamEnumValue value="both">The driver will set DTR and RTS</ParamEnumValue>
           <ParamEnumValue value="none">The driver will clear DTR and RTS</ParamEnumValue>
         </ParamEnumValueList>
      </ParamEnum>
    </ParamList>
  </Driver>


  <Driver name="blazer_usb">
    <Description>For Blazer, Energy Sistem, Fenton Technologies, Mustek and many others with usb connection.</Description>
    <Port type="usb" auto="only">
      <PortSpeed value="un"/>
      <PortBits value ="un"/>
    </Port>
    <ParamList>
      <ParamString force="no" name="norating" variable="no"/>
      <ParamString force="no" name="novendor" variable="no"/>
      <ParamString force="no" name="runtimecal" variable="yes"/>
      <ParamNumber force="no" name="offdelay">
        <ParamNumberDefault value="120"/>
      </ParamNumber>
      <ParamNumber force="no" name="ondelay">
        <ParamNumberDefault value="3"/>
      </ParamNumber>
      <ParamString force="no" name="chargetime" variable="yes"/>
      <ParamString force="no" name="idleload" variable="yes"/>
      <ParamString force="no" name="vendorid" variable="yes"/>
      <ParamString force="no" name="productid" variable="yes"/>
      <ParamString force="no" name="vendor" variable="yes"/>
      <ParamString force="no" name="serial" variable="yes"/>
