=== danpr/knut/knutsetting4/xmlconf/upses.dtd
<?xml version="1.0" ?>
<!ELEMENT Upses (Model+)>
<!ATTLIST Upses count NMTOKEN #REQUIRED>
<!ELEMENT Model (ManufactNameList, ModelNameList, DriverName,DriverNoLock?,DriverMaxStartDelay?,ParamDefList?,Desc?)>
<!ATTLIST Model pref NMTOKEN #REQUIRED>
<!ELEMENT ManufactNameList (ManufactName+)>
<!ELEMENT ManufactName EMPTY>
<!ATTLIST ManufactName value CDATA #REQUIRED>
<!ELEMENT ModelNameList (ModelName+)>
<!ELEMENT ModelName EMPTY>
<!ATTLIST ModelName value CDATA #REQUIRED>
<!ELEMENT DriverName EMPTY>
<!ATTLIST DriverName name CDATA #REQUIRED>
<!ATTLIST DriverName port ( serial | usb ) #REQUIRED>
<!ELEMENT DriverNoLock EMPTY>
<!ELEMENT DriverMaxStartDelay EMPTY>
<!ATTLIST DriverMaxStartDelay value NMTOKEN #REQUIRED>
<!ELEMENT ParamDefList (paramDef+)>
<!ELEMENT ParamDef EMPTY>
<!ATTLIST ParamDef name NMTOKEN #REQUIRED>
<!ATTLIST ParamDef value CDATA #REQUIRED>
<!ELEMENT Description (#PCDATA)

=== danpr/knut/knutsetting4/xmlconf/upses_def.xml
<?xml version="1.0"?>
<!DOCTYPE Upses SYSTEM "upses.dtd">

<Upses count="10">



  <Model pref="100">
    <ManufactNameList>
      <ManufactName value="Ablerex"/>
    </ManufactNameList>
    <ModelNameList>
      <ModelName value="MS-RT"/>
      <ModelName value="Hope Office 400/600"/>
    </ModelNameList>
    <DriverName name="blazer_ser" port="serial"/>
  </Model>



  <Model pref="100">
    <ManufactNameList>
      <ManufactName value="Ablerex"/>
    </ManufactNameList>
    <ModelNameList>
      <ModelName value="625L"/>
      <ModelName value="USB"/>
    </ModelNameList>
    <DriverName name="blazer_usb" port="usb"/>
  </Model>


  <Model pref="100">
    <ManufactNameList>
      <ManufactName value="ActivePower"/>
    </ManufactNameList>
    <ModelNameList>
      <ModelName value="400VA"/>
      <ModelName value="1400VA"/>
      <ModelName value="2000VA"/>
    </ModelNameList>
    <DriverName name="blazer_ser" port="serial"/>
  </Model>


  <Model pref="100">
    <ManufactNameList>
      <ManufactName value="Advice"/>
    </ManufactNameList>
    <ModelNameList>
      <ModelName value="TopGuard 2000"/>
    </ModelNameList>
    <DriverName name="blazer_ser" port="serial"/>
  </Model>

  <Model pref="100">
    <ManufactNameList>
      <ManufactName value="AEC"/>
    </ManufactNameList>
    <ModelNameList>
      <ModelName value="MiniGuard UPS 700"/>
      <ModelName value="Megatec M2501 cable"/>
    </ModelNameList>
    <DriverName name="genericups" port="serial"/>
    <ParamDefList>
      <ParamDef name="upstype" value="21"/>
      <ParamDef name="mfr" value="AEC"/>
    </ParamDefList>
  </Model>



  <Model pref="100">
    <ManufactNameList>
      <ManufactName value="AEG Power Solutions"/>
    </ManufactNameList>
    <ModelNameList>
      <ModelName value="PROTECT HOME"/>
    </ModelNameList>
    <DriverName name="blazer_ser" port="serial"/>
  </Model>


  <Model pref="100">
    <ManufactNameList>
      <ManufactName value="AEG Power Solutions"/>
    </ManufactNameList>
    <ModelNameList>
      <ModelName value="PROTECT HOME"/>
    </ModelNameList>
    <DriverName name="blazer_usb" port="usb"/>
  </Model>



  <Model pref="100">
    <ManufactNameList>
      <ManufactName value="APC"/>
    </ManufactNameList>
    <ModelNameList>
      <ModelName value="Smart-UPS 620"/>
      <ModelName value="Smart-UPS 700"/>
      <ModelName value="Smart-UPS 1000"/>
      <ModelName value="Back-UPS Pro"/>
      <ModelName value="Matrix-UPS"/>
    </ModelNameList>
    <DriverName name="apcsmart" port="serial"/>
  </Model>


  <Model pref="100">
    <ManufactNameList>
      <ManufactName value="APC"/>
    </ManufactNameList>
    <ModelNameList>
      <ModelName value="Back-UPS Pro USB"/>
      <ModelName value="Back-UPS USB"/>
      <ModelName value="Back-UPS RS USB"/>
      <ModelName value="Back-UPS LS USB"/>
      <ModelName value="Back-UPS ES/CyberFort 350"/>
      <ModelName value="Back-UPS BF500"/>
      <ModelName value="BACK-UPS XS LCD"/>
      <ModelName value="Smart-UPS USB"/>
    </ModelNameList>
    <DriverName name="usbhid-ups" port="usb"/>
  </Model>



  <Model pref="100">
    <ManufactNameList>
      <ManufactName value="APC"/>
    </ManufactNameList>
    <ModelNameList>
      <ModelName value="Back-UPS"/>
    </ModelNameList>
    <DriverName name="genericups" port="serial"/>
    <ParamDefList>
      <ParamDef name="upstype" value="1"/>
      <ParamDef name="mfr" value="APC"/>
      <ParamDef name="model" value="Back-UPS"/>
    </ParamDefList>
    <Description>Use 940-0095A/C cables </Description>
  </Model>



  <Model pref="100">
    <ManufactNameList>
      <ManufactName value="APC"/>
    </ManufactNameList>
    <ModelNameList>
      <ModelName value="Back-UPS"/>
    </ModelNameList>
    <DriverName name="genericups" port="serial"/>
    <ParamDefList>
      <ParamDef name="upstype" value="2"/>
      <ParamDef name="mfr" value="APC"/>
      <ParamDef name="model" value="Back-UPS"/>
    </ParamDefList>
    <Description>Use 940-0020B/C cables </Description>
  </Model>




  <Model pref="100">
    <ManufactNameList>
      <ManufactName value="APC"/>
    </ManufactNameList>
    <ModelNameList>
      <ModelName value="Back-UPS"/>
    </ModelNameList>
    <DriverName name="genericups" port="serial"/>
    <ParamDefList>
      <ParamDef name="upstype" value="9"/>
      <ParamDef name="mfr" value="APC"/>
      <ParamDef name="model" value="Back-UPS"/>
    </ParamDefList>
    <Description>Use 940-0023A cables </Description>
  </Model>



  <Model pref="100">
    <ManufactNameList>
      <ManufactName value="APC"/>
    </ManufactNameList>
    <ModelNameList>
      <ModelName value="Back-UPS Office"/>
    </ModelNameList>
    <DriverName name="genericups" port="serial"/>
    <ParamDefList>
      <ParamDef name="upstype" value="12"/>
      <ParamDef name="mfr" value="APC"/>
      <ParamDef name="model" value="Back-UPS Office"/>
    </ParamDefList>
    <Description>Use 940-0023A cables </Description>
  </Model>



  <Model pref="100">
    <ManufactNameList>
      <ManufactName value="APC"/>
    </ManufactNameList>
    <ModelNameList>
      <ModelName value="Back-UPS RS 500"/>
    </ModelNameList>
    <DriverName name="genericups" port="serial"/>
    <ParamDefList>
      <ParamDef name="upstype" value="20"/>
      <ParamDef name="mfr" value="APC"/>
      <ParamDef name="model" value="Back-UPS RS 500"/>
    </ParamDefList>
    <Description>Use custom non-USB cables </Description>
  </Model>




  <Model pref="100">
    <ManufactNameList>
      <ManufactName value="APC"/>
    </ManufactNameList>
    <ModelNameList>
      <ModelName value="Masterswitch"/>
    </ModelNameList>
    <DriverName name="genericups" port="serial"/>
    <ParamDefList>
      <ParamDef name="upstype" value="12"/>
      <ParamDef name="mfr" value="APC"/>
      <ParamDef name="model" value="Masterswitch"/>
    </ParamDefList>
    <Description>Use 940-0020 cables </Description>
  </Model>



  <Model pref="100">
    <ManufactNameList>
      <ManufactName value="Apollo"/>
    </ManufactNameList>
    <ModelNameList>
      <ModelName value="1000A"/>
      <ModelName value="1000F"/>
    </ModelNameList>
    <DriverName name="genericups" port="serial"/>
    <ParamDefList>
      <ParamDef name="upstype" value="4"/>
      <ParamDef name="mfr" value="Apollo"/>
    </ParamDefList>
  </Model>



  <Model pref="100">
    <ManufactNameList>
      <ManufactName value="ARTronic"/>
    </ManufactNameList>
    <ModelNameList>
      <ModelName value="Millenium 1/2/3/6/10 kVA"/>
      <ModelName value="Millenium 3.1 10/15/20 kVA"/>
      <ModelName value="Titanium 6/10 kVA"/>
      <ModelName value="Titanium 3.1 10/15/20 kV"/>
      <ModelName value="Optimum 1/2/3/6/10 kVA"/>
      <ModelName value="Titanium Plus 1/2/3 kVA"/>
    </ModelNameList>
    <DriverName name="blazer_ser" port="serial"/>
  </Model>


  <Model pref="100">
    <ManufactNameList>
      <ManufactName value="ARTronic"/>
    </ManufactNameList>
    <ModelNameList>
      <ModelName value="Titanium Plus 1/2/3 kVA"/>
      <ModelName value="Platinium 6/10 kVA"/>
      <ModelName value="Platinium Combo 3.1 10/15/20 kVA"/>
      <ModelName value="Platinium RT 1/2/3/6/10 kVA"/>
    </ModelNameList>
    <DriverName name="blazer_usb" port="usb"/>
  </Model>


  <Model pref="100">
    <ManufactNameList>
      <ManufactName value="ATEK"/>
    </ManufactNameList>
    <ModelNameList>
      <ModelName value="Defensor 1K"/>
      <ModelName value="Defensor 2K"/>
      <ModelName value="Defensor 3K"/>
      <ModelName value="Defensor 6K"/>
      <ModelName value="Defensor 10K"/>
    </ModelNameList>
    <DriverName name="blazer_usb" port="usb"/>
  </Model>


  <Model pref="100">
    <ManufactNameList>
      <ManufactName value="Atlantis Land"/>
    </ManufactNameList>
    <ModelNameList>
      <ModelName value="A03-P826"/>
    </ModelNameList>
    <DriverName name="blazer_ser" port="serial"/>
  </Model>



  <Model pref="100">
    <ManufactNameList>
      <ManufactName value="Belkin"/>
    </ManufactNameList>
    <ModelNameList>
      <ModelName value="Active Battery Backup BU30 series"/>
      <ModelName value="F6S600auUSB"/>
    </ModelNameList>
    <DriverName name="blazer_usb" port="usb"/>
  </Model>

  <Model pref="100">
    <ManufactNameList>
      <ManufactName value="Belkin"/>
    </ManufactNameList>
    <ModelNameList>
      <ModelName value="Home Office F6H350-SER"/>
      <ModelName value="Home Office F6H500-SER"/>
      <ModelName value="Home Office F6H650-SER"/>
    </ModelNameList>
    <DriverName name="genericups" port="serial"/>
    <ParamDefList>
      <ParamDef name="upstype" value="7"/>
      <ParamDef name="mfr" value="Belkin"/>
    </ParamDefList>
  </Model>

  <Model pref="100">
    <ManufactNameList>
      <ManufactName value="Belkin"/>
    </ManufactNameList>
    <ModelNameList>
      <ModelName value="F6H375-USB"/>
      <ModelName value="Universal UPS F6C1200-UNV"/>
      <ModelName value="Universal UPS F6C1100-UNV"/>
      <ModelName value="Universal UPS F6C1200-UNV"/>
    </ModelNameList>
    <DriverName name="usbhid-ups" port="usb"/>
    <ParamDefList>
      <ParamDef name="vendorid" value="050d"/>
    </ParamDefList>
  </Model>

  <Model pref="100">
    <ManufactNameList>
      <ManufactName value="Belkin"/>
    </ManufactNameList>
    <ModelNameList>
      <ModelName value="F6H375-USB"/>
      <ModelName value="Universal UPS F6C1100-UNV"/>
      <ModelName value="Universal UPS F6C1200-UNV"/>
    </ModelNameList>
    <DriverName name="blazer_usb" port="usb"/>
    <ParamDefList>
      <ParamDef name="vendorid" value="0665"/>
    </ParamDefList>
  </Model>


  <Model pref="100">
    <ManufactNameList>
      <ManufactName value="Belkin"/>
    </ManufactNameList>
    <ModelNameList>
      <ModelName value="F6C1500-TW-RK"/>
      <ModelName value="Office Series F6C550-AVR"/>
      <ModelName value="Universal UPS F6C100-UNV"/>
      <ModelName value="Universal UPS F6C120-UNV"/>
